services:
  mongodb:
    image: "mongo:8.2.5"
    restart: "on-failure"
    networks:
      - graylog
    volumes:
      - "./.mongodb_data:/data/db"
      - "./.mongodb_config:/data/configdb"

  # ⚠️ Make sure this is set on the host before starting:
  # echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
  # sudo sysctl -p
  datanode:
    image: "graylog/graylog-datanode:7.0.4"
    hostname: "datanode"
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: "/var/lib/graylog-datanode/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_DATANODE_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_DATANODE_MONGODB_URI: "mongodb://mongodb:27017/graylog"
#      GRAYLOG_DATANODE_JAVA_OPTS: "-Xms7g -Xmx7g"
#      GRAYLOG_DATANODE_MAX_MEMORY: "7g"
#      OPENSEARCH_JAVA_OPTS: "-Xms7g -Xmx7g"
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:8999:8999/tcp"   # DataNode API
      - "127.0.0.1:9200:9200/tcp"
      - "127.0.0.1:9300:9300/tcp"
    networks:
      - graylog
    volumes:
      - "./storage/.graylog-datanode:/var/lib/graylog-datanode"
      - "./jvm.options:/etc/graylog/datanode/jvm.options"
      - "./datanode.conf:/etc/graylog/datanode/datanode.conf"
    restart: "on-failure"

  graylog:
    hostname: "server"
    image: "graylog/graylog:7.0.4"
    depends_on:
      mongodb:
        condition: "service_started"
      datanode:
        condition: "service_started"
    entrypoint: "/usr/bin/tini --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      # GRAYLOG_DATANODE_PASSWORD_SECRET and GRAYLOG_PASSWORD_SECRET MUST be the same value
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2}"
      TZ: "Europe/Paris"
      GRAYLOG_ROOT_TIMEZONE: "Europe/Paris"
#      GRAYLOG_SERVER_JAVA_OPTS: "-Xms2g -Xmx2g -server -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow"
#      GRAYLOG_SERVER_JAVA_OPTS: "-Xms2g -Xmx2g -server -XX:+UseG1GC -XX:-OmitStackTraceInFastThrow -Dmail.smtps.ssl.trust=* -Dmail.smtps.ssl.checkserveridentity=false"
      GRAYLOG_VERSION_CHECK_ENABLED: "false"
      GRAYLOG_SERVER_JAVA_OPTS: "-Xms2g -Xmx2g -server -XX:+UseG1GC -Dmail.smtp.ssl.trust=* -Dmail.smtps.ssl.trust=* -Dmail.smtp.ssl.checkserveridentity=false -Dmail.smtps.ssl.checkserveridentity=false"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "https://SVPL01-SVLOG-03.cgo.local/"
      # Configuration SMTP
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_TLS_TRUST_ALL: "true"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "10.100.20.7"
      GRAYLOG_TRANSPORT_EMAIL_PORT: 587
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "true"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "true"
#      GRAYLOG_TRANSPORT_EMAIL_PORT: 465
#      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
#      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "true"
      GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: "${GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME}"
      GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: "${GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD}"
      GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX: "[Graylog]"
      GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL: "${GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME}"
      GRAYLOG_TRANSPORT_FROM_EMAILNAME: "Graylog Alerting"

      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
    ports:
    - "5044:5044/tcp"   # Beats
    - "514:5140/udp"   # Syslog
    - "514:5140/tcp"   # Syslog
#    - "5555:5555/tcp"   # RAW TCP
#    - "5555:5555/udp"   # RAW UDP
    - "9000:9000/tcp"   # Server API
#    - "12201:12201/tcp" # GELF TCP
#    - "12201:12201/udp" # GELF UDP
    #- "127.0.0.1:10000:10000/tcp" # Custom TCP port
    #- "127.0.0.1:10000:10000/udp" # Custom UDP port
    - "13301:13301/tcp" # Forwarder data
    - "13302:13302/tcp" # Forwarder config
    networks:
      - graylog
    volumes:
      # IMPORTANT: bind mounts (e.g., "./data:/usr/share/graylog/data") currently
      # don't work correctly. You have to use volume mounts.
      # See: https://github.com/Graylog2/docker-compose/issues/99#issuecomment-3800898829
      - "./.graylog_data:/usr/share/graylog/data/data"
      - "./storage/.graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"

networks:
  graylog:
    driver: "bridge"

volumes:
  .mongodb_data:
  .mongodb_config:
  .graylog-datanode:
  .graylog_data:
